# Generated by Django 6.0.1 on 2026-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='anonymous_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
