# Generated by Django 6.0.1 on 2026-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_anonymous_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='is_admin_response',
            field=models.BooleanField(default=False),
        ),
    ]
