# Generated by Django 6.0.1 on 2026-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='user', max_length=20),
        ),
    ]
