"""
Django settings for campusFix project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: load secret and runtime flags from environment
# In production set DJANGO_SECRET_KEY and DJANGO_DEBUG=False and ALLOWED_HOSTS
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@)ml4gb3$w57e))k07ldfdhfh5g87flsae-le45^3vz*y3u%&r",
)

# DEBUG should be False in production. For local development default to True
# (set DJANGO_DEBUG=False in production environment variables).
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# ALLOWED_HOSTS can be provided as a comma-separated env var, e.g. ALLOWED_HOSTS=example.com,api.example.com
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Optional: CSRF trusted origins (comma-separated)
raw_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if raw_csrf:
    CSRF_TRUSTED_ORIGINS = [u.strip() for u in raw_csrf.split(",") if u.strip()]

# During local development (DEBUG=True) include 0.0.0.0 so runserver bound to that
# can be accessed via http://0.0.0.0:8000/ without a Bad Request (400).
if DEBUG and "0.0.0.0" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("0.0.0.0")

# Also include 0.0.0.0 to allow binding runserver to that address during testing
if "0.0.0.0" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("0.0.0.0")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "user_dashboard",
    "issues",
    "accounts",
    "admin_dashboard",
    "super_admin_dashboard",
    "grappelli",  # Django Grappelli for enhanced admin interface
    # Security apps
    "axes",
    "csp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Axes middleware should be enabled to monitor auth attempts
    "axes.middleware.AxesMiddleware",
    # CSP middleware
    "csp.middleware.CSPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Axes & auth backend: place Axes backend before default to allow blocking
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "campusFix.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "campusFix/templates", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "campusFix.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Use dj-database-url to parse DATABASE_URL in production (Postgres)
try:
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(
        os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
    )
except Exception:
    # dj-database-url not installed or parse failed; fall back to sqlite
    pass


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Location where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"
# Use WhiteNoise storage for compressed static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/accounts/redirect/"
LOGOUT_REDIRECT_URL = "login"

# Email configuration - Brevo API (via environment variables)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)

# Default from address used for outgoing emails
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "CampusFix <onboarding@campusfix.tk>"
)

# Password reset token timeout (in seconds) - default is 3 days
PASSWORD_RESET_TIMEOUT = 3 * 24 * 60 * 60

# -----------------------
# Security hardening (production)
# -----------------------
# Treat secure cookies and other headers
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "True") == "True"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "True") == "True"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True
# XSS filter
SECURE_BROWSER_XSS_FILTER = True
# Frame options
X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")

# Disable automatic HTTPS redirects for now so local and test access uses HTTP.
# In production you should enable HTTPS and HSTS via environment configuration.
SECURE_SSL_REDIRECT = False
# Disable HSTS headers while testing locally to avoid browsers expecting HTTPS.
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# When behind a proxy/load balancer that sets X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Recommended: set these in your production environment. Local dev can override with env vars.

# -----------------------
# django-axes settings (brute-force protection)
# -----------------------
AXES_ENABLED = os.environ.get("AXES_ENABLED", "True") == "True"
AXES_FAILURE_LIMIT = int(os.environ.get("AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = int(os.environ.get("AXES_COOLOFF_TIME", "900"))  # seconds
# Note: newer django-axes versions deprecate some older settings. Using defaults
# or newer configuration keys in production is recommended.

# -----------------------
# django-csp policy (v4+ format)
# -----------------------
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'", "https://cdnjs.cloudflare.com"),
        "style-src": (
            "'self'",
            "https://fonts.googleapis.com",
            "https://cdnjs.cloudflare.com",
        ),
        "font-src": (
            "'self'",
            "https://fonts.gstatic.com",
            "https://cdnjs.cloudflare.com",
            "https://use.fontawesome.com",
            "data:",
        ),
    }
}

# In development allow inline styles and scripts because many templates use
# inline `style="..."` attributes and small inline scripts. Keep CSP strict
# in production by not setting DJANGO_DEBUG to True.
if DEBUG:
    directives = CONTENT_SECURITY_POLICY.setdefault("DIRECTIVES", {})
    style_src = directives.get("style-src", ("'self'",))
    script_src = directives.get("script-src", ("'self'",))
    if "'unsafe-inline'" not in style_src:
        directives["style-src"] = tuple(list(style_src) + ["'unsafe-inline'"])
    if "'unsafe-inline'" not in script_src:
        directives["script-src"] = tuple(list(script_src) + ["'unsafe-inline'"])
